### ISSUE TITLE
Create The Home Page 🏠

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Impact-Wall#1]
Lets Go ! 🔥

**Comment by Upendra2003** [comment]
Hey @MedouneSGB I can do this but can you explain more about the home page.

**Comment by MedouneSGB** [comment]
Hello @Upendra2003,
For the home page we need :
- A Navbar with the logo Impact Wall and a menu Home & Participate.
- A Header With a swmall text and a research bar
- For the main content it will be cards 4 clickable colomns of highlighted person or organisation (image et name).
- Then a footer

**Comment by vanshika8750** [comment]
i want to do this. please assign it to me

**Comment by MedouneSGB** [comment]
For the color code we will try to use the same as hacktoberfest23.
Black and Gold or Yellow.


![hf10_banner_1032x600](https://github.com/MedouneSGB/Impact-Wall/assets/40875400/f355d029-3a78-4717-b58d-1cd08a919d1a)

**Comment by MedouneSGB** [comment]
Hi @vanshika8750, 
Can you try the issue #2

**Comment by Upendra2003** [comment]
I will do this @MedouneSGB thank you for assigning this.
