### ISSUE TITLE
Create highlighted person or organisation description page 🖼️

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Impact-Wall#2]
This page will be the description page for each person or org added.
It will have contain the name, image and description.

**Comment by vanshika8750** [comment]
i will do this. pls assign it to me

**Comment by MedouneSGB** [comment]
Hello @vanshika8750  are you still working on it ?

**Comment by vanshika8750** [comment]
no

**Comment by alphakahere** [comment]
Hello @MedouneSGB, I take it

**Comment by MedouneSGB** [comment]
Lets Gp ! 💯🔥

**Comment by MedouneSGB** [comment]
Good Job ! 🚀✨
