### ISSUE TITLE
Add the website icon

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Impact-Wall#4]
We should use this hacktoberfest pin to the website icon.
![11@1x](https://github.com/MedouneSGB/Impact-Wall/assets/40875400/0dd6628e-766c-4560-99a7-21ee25ebef5d)

**Comment by bishwobista** [comment]
assign me

**Comment by MedouneSGB** [comment]
Hi @bishwobista I just did it try another issue.

**Comment by MedouneSGB** [comment]
@bishwobista you should try #8 or #6
