### ISSUE TITLE
Create the contributors page 😎

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Impact-Wall#6]
We need a contributors page showing the profiles that contributed. 💯

**Comment by maida12** [comment]
can I do this?

**Comment by MedouneSGB** [comment]
Yes but, I assigned you to #5
Do you wanna change ?

**Comment by maida12** [comment]
no

**Comment by maida12** [comment]
Can I do this now?

**Comment by MedouneSGB** [comment]
Hi @maida12 
Yes 💯

**Comment by MedouneSGB** [comment]
Hi @maida12 
You're still working on it ?

**Comment by maida12** [comment]
yes

**Comment by MedouneSGB** [comment]
Good Job !
